version: 1
sources:
  - name: unicorns
    table: main.unicorns
    connection:
      type: motherduck
      identifier: md:my_db
      alias: md:my_db
      readOnly: false
      duckdbExtension: motherduck
  - name: recipes
    table: public.recipes
    connection:
      type: postgres
      identifier: host=127.0.0.1 port=54322 user=postgres password=REDACTED_LOCAL dbname=postgres
      alias: host=127.0.0.1 port=54322 user=postgres password=REDACTED_LOCAL dbname=postgres
      readOnly: true
      duckdbExtension: postgres
  - name: keywords
    table: public.keywords
    connection:
      type: postgres
      identifier: host=167.235.227.188 port=5432 user=admin password=REDACTED dbname=main
      alias: host=167.235.227.188 port=5432 user=admin password=REDACTED dbname=main
      readOnly: true
      duckdbExtension: postgres
  - name: saved_keywords
    table: public.saved_keywords
    connection:
      type: postgres
      identifier: host=167.235.227.188 port=5432 user=admin password=REDACTED dbname=main
      alias: host=167.235.227.188 port=5432 user=admin password=REDACTED dbname=main
      readOnly: true
      duckdbExtension: postgres
