version: 1
sources:
  - name: unicorns
    table: main.unicorns
    connection:
      type: motherduck
      identifier: md:my_db
      alias: just_a_dataset_with_unicorns
      readOnly: false
      duckdbExtension: motherduck
